---
booktitle: Proceedings of the NeurIPS 2020 Competition and Demonstration Track
shortname: NeurIPSCDT
volume: '133'
year: '2021'
start: 2020-12-06
end: 2020-12-12
published: 2021-08-07
url: http://proceedings.mlr.press
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: NeurIPSCDT-2020
month: 0
cycles: false
bibtex_editor: Escalante, Hugo Jair and Hofmann, Katja
editor:
- given: Hugo Jair
  family: Escalante
- given: Katja
  family: Hofmann
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the NeurIPS 2020 Competition and Demonstration Track
    Held in Virtual on 06-12 December 2020

  Published as Volume 133 by the Proceedings of Machine Learning Research on 07 August 2021.

  Volume Edited by:
    Hugo Jair Escalante
    Katja Hofmann

  Series Editors:
    Neil D. Lawrence
    * Mark Reid
date_str: 06--12 Dec
author:
  name: PMLR
baseurl: "/v133"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v133
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v133
email: ''
conference:
  name: NeurIPS 2020 Competition and Demonstration Track
  url:
  location: Virtual
  dates:
  - 2020-12-06
  - 2020-12-07
  - 2020-12-08
  - 2020-12-09
  - 2020-12-10
  - 2020-12-11
  - 2020-12-12
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v133/NeurIPSCDT-2020.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v133/NeurIPSCDT-2020.bib
